Kolesa modifications
kolesa-team/objective-c-style-guide pull request #1
Opened 2018-02-23 08:28 UTC by realvadim

1) Исправил ошибки, что были в исходном репо;

2) Дополнил положениями, которые приняты в "Колесах".

2018-02-28 09:04 UTC, iamirzhan approved these changes

2018-03-02 10:48 UTC, tabynbayev requested changes

2018-03-02 10:48 UTC, tabynbayev commented on README.md
> +* A `nullable` method parameter highlights that a passed value can turn out to be a `nil`, even if it is not explicitly `nullable` (for instance, `NSDictionary` values accessed by keys); Likewise, on
лучше убрать строчки 525-529 пока. Там не все верно. Потом распишем в другом PR, чтобы все было корректно.

2018-03-03 04:25 UTC, realvadim commented on README.md
> +* A `nullable` method parameter highlights that a passed value can turn out to be a `nil`, even if it is not explicitly `nullable` (for instance, `NSDictionary` values accessed by keys); Likewise, on
Готово

2018-03-03 04:46 UTC, tabynbayev approved these changes

2018-03-03 04:47 UTC, merged